# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyClick < Formula
  desc "High-performance Go TUI for project management systems."
  homepage "https://github.com/losty17/lazy-click"
  version "0.1.0-alpha.4"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-alpha.4/lazy-click_0.1.0-alpha.4_darwin_x86_64.tar.gz"
      sha256 "d3d26fd4fcc451042697197860e42ca64a5c4dec9434add1f969c08c1c7c31d7"

      define_method(:install) do
        bin.install "lazy-click"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-alpha.4/lazy-click_0.1.0-alpha.4_darwin_arm64.tar.gz"
      sha256 "acff9416ceaf2793beaf131e779efcf39cbd8c0dae945f7dd9ac2df09bdd5a49"

      define_method(:install) do
        bin.install "lazy-click"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-alpha.4/lazy-click_0.1.0-alpha.4_linux_x86_64.tar.gz"
      sha256 "39af919a6a68cda17772bd2ac57bb51402b74ec4f5b3e4843784ddeed8f81252"
      define_method(:install) do
        bin.install "lazy-click"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-alpha.4/lazy-click_0.1.0-alpha.4_linux_arm64.tar.gz"
      sha256 "767d0530705474c050ffbd6f1fb813013286fce0feef91d13cb63aa52f5573ff"
      define_method(:install) do
        bin.install "lazy-click"
      end
    end
  end
end
