# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyClick < Formula
  desc "High-performance Go TUI for project management systems."
  homepage "https://github.com/losty17/lazy-click"
  version "0.1.0-beta.6"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-beta.6/lazy-click_0.1.0-beta.6_darwin_x86_64.tar.gz"
      sha256 "9957909a963e65e13af555757f6dd63fe615ac52ba0df016e9e60a49fafc414f"

      define_method(:install) do
        bin.install "lazy-click"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-beta.6/lazy-click_0.1.0-beta.6_darwin_arm64.tar.gz"
      sha256 "cfbca9f5dec26ee65450c5ac799d676d6f5524dfc739329fa6006d13adb659f7"

      define_method(:install) do
        bin.install "lazy-click"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-beta.6/lazy-click_0.1.0-beta.6_linux_x86_64.tar.gz"
      sha256 "aeddb8924025b4430de6a2028bc55fcd462526552fb9e4a6c9fa9e0054893c20"
      define_method(:install) do
        bin.install "lazy-click"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/losty17/lazy-click/releases/download/v0.1.0-beta.6/lazy-click_0.1.0-beta.6_linux_arm64.tar.gz"
      sha256 "cf42a15005bfa161e47a98b17158e20601edc57e6ce2eaeaa1d3f287d9ca0f39"
      define_method(:install) do
        bin.install "lazy-click"
      end
    end
  end
end
